%Estimates sound surface, based on signals heard

% Locations to sample sound (m)
x_coords_to_sample_sound = 0:SURFACE_SAMPLING_PERIOD:SURFACE_WIDTH;
y_coords_to_sample_sound = 0:SURFACE_SAMPLING_PERIOD:SURFACE_HEIGHT;
z_coords_to_sample_sound = [-10, 0, 1000];

sound_surface = estimateSoundSurface( ...
                                x_coords_to_sample_sound, ...
                                y_coords_to_sample_sound, ...
                                z_coords_to_sample_sound, ...
                                listeners_signals, LISTENERS_LOCATIONS, ...
                                SAMPLING_RATE, ...
                                SPEED_OF_SOUND, ...
                                WATCH_SIGNALS ...
                            );
 
% % surfaceOfSignals = normalizeSurfaceOfSignals(surfaceOfSignals);
% 
% figure();
% % graphLocs(LISTENER_LOCS, LISTENER_COLORS, ...
% %     SURFACE_MIN_X, SURFACE_MAX_X, SURFACE_MIN_Y, SURFACE_MAX_Y);
% hold on;
% graphSurfaceSignals(x_vals, y_vals, sound_surface);
% hold on;
% graphLocs(LISTENER_LOCS, LISTENER_COLORS, SURFACE_MIN_X, SURFACE_MAX_X, SURFACE_MIN_Y, SURFACE_MAX_Y);
% % EMITTER_LOCS = [EMITTER_LOC;];
% graphLocs(EMITTER_LOC,POINT_COLORS, SURFACE_MIN_X, SURFACE_MAX_X, SURFACE_MIN_Y, SURFACE_MAX_Y);
% 
