% Simulate listener signals

listeners_signals = simulateListenersSignalsGivenOneEmission( ...
                            LISTENERS_LOCATIONS, ...
                            RECORDING_DURATION, ...
                            SAMPLING_RATE, ...
                            ...
                            SOUND_EMITTER_TIMESTAMP, ...
                            SOUND_EMITTER_LOCATION, ...
                            SPEED_OF_SOUND, ...
                            MAX_NOISE ...
                        );