% Simulates listeners signals


listener_signals = simulateSignalsGivenOneEmission( ...
                            EMITTER_LOCATION, ...
                            audiorecorderToSignal(mainSound), ...
                            SAMPLE_RATE, ...
                            LISTENER_LOCATIONS);


